# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepface.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x65\x65pface.proto\x12\x08\x64\x65\x65pface\"9\n\x12\x46indSimilarRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x62_path\x18\x02 \x01(\t\"5\n\x0bSimilarFace\x12\x12\n\nimage_path\x18\x01 \x01(\t\x12\x12\n\nsimilarity\x18\x02 \x01(\x02\"(\n\x13\x46indSimilarResponse\x12\x11\n\tfile_path\x18\x01 \x01(\t2`\n\x0b\x46\x61\x63\x65Service\x12Q\n\x10\x46indSimilarFaces\x12\x1c.deepface.FindSimilarRequest\x1a\x1d.deepface.FindSimilarResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deepface_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FINDSIMILARREQUEST']._serialized_start=28
  _globals['_FINDSIMILARREQUEST']._serialized_end=85
  _globals['_SIMILARFACE']._serialized_start=87
  _globals['_SIMILARFACE']._serialized_end=140
  _globals['_FINDSIMILARRESPONSE']._serialized_start=142
  _globals['_FINDSIMILARRESPONSE']._serialized_end=182
  _globals['_FACESERVICE']._serialized_start=184
  _globals['_FACESERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
